version: '3'

services:
  node:
    build: .
    container_name: node_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - JWT_SECRET=secretJWT
      - API_HOST='node'
      - API_PORT=3000
      - NODE_ENV='development'
  db:
    container_name: mysql_db
    image: mysql
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10